name: ai_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  google_nav_bar: ^5.0.6
  intl: ^0.18.0
  shimmer: ^3.0.0

  # TensorFlow Lite packages
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1

  image_picker: ^0.8.9
  camera: ^0.10.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/